test:
	python app.py --test -vv

clean:
	rm -f *.pyc
	rm -f test_output_file

functionality:
	python app.py -vv

voice:
	python app.py -v -V

monitors:
	python app.py -v -m

alice:
	python app.py -V -m

alice_verbose:
	python app.py -V -m -v

